---
- hosts: web
  remote_user: virtxpert
  sudo: no
  tasks:
  - name: install httpd latest
    yum: pkg=httpd state=latest
  - name: install php latest
    yum: pkg=php state=latest
    notify:
       - start httpd
	   
  handlers:
      - name: start httpd
        service: name=httpd state=started enabled=yes